---
- name: Gather OS information from all hosts
  hosts: all
  tasks:
    - name: Gather system facts
      ansible.builtin.setup:
        gather_subset:
          - hardware
          - network
          - virtual
          - distribution
          - os_family
          - distribution
      register: system_facts

    - name: Display OS information
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "OS Version: {{ ansible_facts['distribution_version'] }} {{ ansible_facts['distribution'] }}"
          - "OS Family: {{ ansible_facts['os_family'] }}"
