---
- name: Configure duckdns cron
  hosts: homelab

  vars:
    duckdns_install_dir: "/home/{{ ansible_user }}/duckdns"
    duckdns_script_file: "{{ duckdns_install_dir }}/duck_job.sh"
    duckdns_log_file: "{{ duckdns_install_dir }}/duck.log"
    duckdns_script_content: "#!/bin/bash \n\necho url='https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip=' | curl -k -o {{ duckdns_log_file }} -K -"

  vars_files:
    - secure-variables.yml

  tasks:
    - name: Create duckdns directory
      ansible.builtin.file:
        path: "{{ duckdns_install_dir }}"
        state: directory
        mode: '0755'

    - name: Create cron script
      ansible.builtin.copy:
        content: "{{ duckdns_script_content}}"
        dest: "{{ duckdns_script_file }}"

    - name: Ensure duck script is executable
      ansible.builtin.file:
        path: "{{ duckdns_script_file }}"
        mode: '0700'

    - name: Ensure duck dns script is executed each 5 minutes"
      ansible.builtin.cron:
        name: "Update duck dns"
        minute: "15"
        job: "{{ duckdns_script_file }}"