---
- name: Install OS tools
  hosts: all
  become: yes
  tasks:
    - name: Install some helpful tools.
      package:
        name:
          - vim
          - htop
          - powertop
          - docker-compose
          - python3-docker
        state: present
