---
- name: Deploy docker compose
  hosts: homelab

  vars_files:
    - homelab-compose-variables.yml
    - secure-variables.yml

  tasks:
    - name: Tear down existing services.
      community.docker.docker_compose:
        project_src: "{{ compose_install_dir }}"
        state: absent
        remove_volumes: true
      become: yes
      when: compose_remove_services | bool

    - name: Tear down data dirs.
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ compose_pihole_data_dir }}/config"
        - "{{ compose_pihole_data_dir }}/dnsmasq"
        - "{{ compose_ha_data_dir }}/config"
        - "{{ compose_mqtt_data_dir }}/config"
        - "{{ compose_mqtt_data_dir }}/log"
        - "{{ compose_mqtt_data_dir }}/data"
      become: yes
      when: compose_remove_services | bool

    - name: Create installation dir.
      file:
        path: "{{ compose_install_dir }}"
        state: directory
        mode: '0755'

    - name: Create data dirs.
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ compose_pihole_data_dir }}/config"
        - "{{ compose_pihole_data_dir }}/dnsmasq"
        - "{{ compose_ha_data_dir }}/config"
        - "{{ compose_mqtt_data_dir }}/config"
        - "{{ compose_mqtt_data_dir }}/log"
        - "{{ compose_mqtt_data_dir }}/data"
      ignore_errors: true

    - name: Copy docker compose file.
      template:
        src: homelab-docker-compose.yml.j2
        dest: "{{ compose_install_dir }}/docker-compose.yml"

    - name: Copy mosquitto configuration file.
      copy:
        src: ./files/mosquitto.conf
        dest: "{{ compose_mqtt_data_dir }}/config/mosquitto.conf"
        force: no

    - name: Copy mosquitto password file.
      template:
        src: ./templates/mosquitto_users.j2
        dest: "{{ compose_mqtt_data_dir }}/config/mosquitto_users"
        force: no
      register: mosquittousers

    - name: Start services
      community.docker.docker_compose:
        project_src: "{{ compose_install_dir }}"
        state: present
      become: yes

    - name: Configure mosquitto.
      community.docker.docker_container_exec:
        container: "mosquitto"
        command: "mosquitto_passwd -U /mosquitto/config/mosquitto_users"
      become: yes
      when: mosquittousers.changed

    - name: Restart mosquitto a container.
      community.docker.docker_container:
        name: "mosquitto"
        state: started
        restart: true
      become: yes
      when: mosquittousers.changed
