---
- name: Configure bastion host
  hosts: bastion

  vars:
    config_dir: "/home/{{ ansible_user }}/conf"
    web_dir: "/home/{{ ansible_user }}/web"
    media_dir: "/home/{{ ansible_user }}/media"
    template_nginx_conf: "templates/nginx.conf.j2"
    template_passwd: "templates/htpasswd.j2"
    target_nginx_conf: "{{ config_dir }}/nginx.conf"
    target_passwd: "{{ config_dir }}/htpasswd"
    src_web_index_file: "files/index.html"
    dest_web_index_file: "{{ web_dir }}/index.html"
    nginx_exposed_port: 8080
    nginx_web_dir: "/html"
    nginx_media_dir: "/media"
    nginx_conf_file: "/etc/nginx/conf.d/default.conf"
    nginx_passwd_file: "/etc/nginx/.htpasswd"

  vars_files:
    - secure-variables.yml

  tasks:
    - name: Ensure dirs exist.
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ config_dir }}"
        - "{{ web_dir }}"

    - name: Template files.
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "{{ template_nginx_conf }}", dest: "{{ target_nginx_conf }}"}
        - { src: "{{ template_passwd }}", dest: "{{ target_passwd }}"}

    - name: Copy files.
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "{{ src_web_index_file }}", dest: "{{ dest_web_index_file }}"}

    - name: Create nginx container
      containers.podman.podman_container:
        name: nginx
        image: docker.io/nginx:stable-alpine-perl
        state: created
        recreate: true
        hostname: bastion-nginx
        volumes:
          - "{{ target_nginx_conf }}:{{ nginx_conf_file }}:ro,z"
          - "{{ target_passwd }}:{{ nginx_passwd_file }}:ro,z"
          - "{{ media_dir }}:{{ nginx_media_dir }}:z"
          - "{{ web_dir }}:{{ nginx_web_dir }}:ro"
        label:
          type: nginx
          host: bastion
        ports:
          - "{{ nginx_exposed_port }}:80"

    - name: Create cloudflare container
      containers.podman.podman_container:
        name: cloudflare
        image: docker.io/cloudflare/cloudflared:latest
        state: created
        command: "tunnel --no-autoupdate run --token {{ cloudflare_bastion_token }}"
        hostname: bastion-cloudflare
        label:
          type: cloudflare
          host: bastion

    - name: Ensure systemd files for containers exists
      containers.podman.podman_generate_systemd:
        name: "{{ item }}"
        dest: ~/.config/systemd/user/
      with_items:
        - nginx
        - cloudflare

    - name: Podman containers must be started and enabled on systemd
      ansible.builtin.systemd:
        name: "container-{{ item }}"
        scope: user
        daemon_reload: true
        state: started
        enabled: true
      with_items:
        - nginx
        - cloudflare
