---
- name: Keep server up-to-date
  hosts: [omv, docker]
  become: yes
  tasks:
    - name: Update all packages to their latest version.
      package:
        name: "*"
        update-cache: yes
        state: latest