---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure requied packages are installed.
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  register: add_repository_key

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install latest docker packages are installed.
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "started"
    enabled: "true"